name: gaussian_splatting_opacity_reset
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorboard
  - numpy<2
  - gcc_linux-64=11
  - gxx_linux-64=11
  - python=3.9
  - pip
  - tqdm
  - plyfile
  - hdbscan
  - matplotlib
  - cmake
  - pip:
      - torch==1.13.1
      - torchvision==0.14.1
      - open-clip-torch
      - dearpygui
      - opencv-python
      - joblib==1.1.0
      - numpy==1.23.5
